import { Tutor, Skill, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'tech',
    name: 'Technology & Coding',
    iconName: 'Code',
    description: 'Python, React, Data Structures, Git, Web Design',
    skillsCount: 14,
  },
  {
    id: 'design',
    name: 'Design & Creative',
    iconName: 'Palette',
    description: 'Figma, UI/UX, Photoshop, Video Editing, Blender',
    skillsCount: 9,
  },
  {
    id: 'academics',
    name: 'Academics & Math',
    iconName: 'BookOpen',
    description: 'Calculus, Statistics, Physics, Organic Chemistry',
    skillsCount: 12,
  },
  {
    id: 'languages',
    name: 'Languages & Writing',
    iconName: 'Languages',
    description: 'Spanish, Japanese, Public Speaking, Academic Essays',
    skillsCount: 8,
  },
  {
    id: 'business',
    name: 'Business & Finance',
    iconName: 'TrendingUp',
    description: 'Financial Modeling, Excel, Marketing Strategy',
    skillsCount: 6,
  },
];

export const TUTORS: Tutor[] = [
  {
    id: 'tutor_1',
    name: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120&h=120',
    dept: 'Computer Science, Year 3',
    bio: 'Hey, I am Alex! I specialize in full-stack web development and algorithm optimization. I love breaking down complex programming concepts into small, digestible student-friendly pieces. Let me know what you need help with!',
    offeredSkills: ['React & Tailwind CSS', 'Python Data Science', 'Git & Github Basics'],
    learningRequests: ['UI/UX Design UI elements', 'Spanish Conversation'],
    rating: 4.9,
    reviewsCount: 18,
    totalSessions: 42,
    availabilitySchedule: {
      days: ['Mon', 'Wed', 'Fri'],
      hours: '2:00 PM - 6:00 PM',
      slots: [
        { id: 't1_s1', timeString: '02:00 PM - 03:00 PM', isAvailable: true },
        { id: 't1_s2', timeString: '03:15 PM - 04:15 PM', isAvailable: false },
        { id: 't1_s3', timeString: '04:30 PM - 05:30 PM', isAvailable: true },
      ],
    },
    reviews: [
      {
        id: 'rev_1_1',
        reviewerName: 'Sophie Chen',
        reviewerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 5,
        comment: 'Alex was super patient! He helped me debug my final React project and explained state management so clearly. Highly recommend!',
        date: 'May 15, 2026',
        skillName: 'React & Tailwind CSS',
      },
      {
        id: 'rev_1_2',
        reviewerName: 'Jordan Taylor',
        reviewerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 4.8,
        comment: 'Very practical examples for Python pandas. Helped me prep for my midterms and understand standard data science pipelines.',
        date: 'May 08, 2026',
        skillName: 'Python Data Science',
      },
    ],
  },
  {
    id: 'tutor_2',
    name: 'Chloe Tanaka',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=120&h=120',
    dept: 'Digital Arts & Design, Year 4',
    bio: 'Hi there! I am Chloe, a freelance UI/UX designer and design major. I enjoy teaching modern tool workflows like Figma, visual design principles, and custom illustrations. Happy to swap design tips for linear algebra or coding help!',
    offeredSkills: ['Figma UI/UX Prototyping', 'Vector Illustration', 'Branding Foundations'],
    learningRequests: ['Python Programming', 'Investment Portfolios'],
    rating: 5.0,
    reviewsCount: 22,
    totalSessions: 55,
    availabilitySchedule: {
      days: ['Tue', 'Thu'],
      hours: '10:00 AM - 4:00 PM',
      slots: [
        { id: 't2_s1', timeString: '10:00 AM - 11:00 AM', isAvailable: true },
        { id: 't2_s2', timeString: '11:30 AM - 12:30 PM', isAvailable: true },
        { id: 't2_s3', timeString: '01:00 PM - 02:00 PM', isAvailable: true },
        { id: 't2_s4', timeString: '02:30 PM - 03:30 PM', isAvailable: false },
      ],
    },
    reviews: [
      {
        id: 'rev_2_1',
        reviewerName: 'Marcus Brodie',
        reviewerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 5,
        comment: 'Chloe is an absolute Figma wizard! I learned auto-layout and components in just one session. Literally changed my life!',
        date: 'May 20, 2026',
        skillName: 'Figma UI/UX Prototyping',
      },
    ],
  },
  {
    id: 'tutor_3',
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120&h=120',
    dept: 'Mechanical Engineering, Year 3',
    bio: 'Hi! I am David. Physics and Calculus can be intimidating, but we can make them easier together. I specialize in explaining complex engineering concepts, structural analysis, and standard calculus methods.',
    offeredSkills: ['Calculus I & II Prep', 'Physics: Mechanics', '3D Modeling (SolidWorks)'],
    learningRequests: ['React & Frontend', 'Figma Prototyping'],
    rating: 4.8,
    reviewsCount: 15,
    totalSessions: 30,
    availabilitySchedule: {
      days: ['Sat', 'Sun'],
      hours: '11:00 AM - 5:00 PM',
      slots: [
        { id: 't3_s1', timeString: '11:00 AM - 12:00 PM', isAvailable: true },
        { id: 't3_s2', timeString: '01:00 PM - 02:00 PM', isAvailable: true },
        { id: 't3_s3', timeString: '03:00 PM - 04:00 PM', isAvailable: true },
      ],
    },
    reviews: [
      {
        id: 'rev_3_1',
        reviewerName: 'Lina Peterson',
        reviewerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 4.5,
        comment: 'Great calculus tutor. He simplified integration by parts using visual representations. Appreciated his diagrams!',
        date: 'May 18, 2026',
        skillName: 'Calculus I & II Prep',
      },
    ],
  },
  {
    id: 'tutor_4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=120&h=120',
    dept: 'Applied Linguistics, Year 2',
    bio: 'Bonjour! Hola! Hello! I am Elena. I am native bilingual in Russian and Spanish, and an Applied Linguistics student. I believe language learning is all about active conversation. Let us practice natural dialog together!',
    offeredSkills: ['Spanish Conversational Skills', 'Russian for Beginners', 'Essay Proofreading'],
    learningRequests: ['Python Coding', 'Video Editing'],
    rating: 4.7,
    reviewsCount: 12,
    totalSessions: 25,
    availabilitySchedule: {
      days: ['Wed', 'Thu', 'Fri'],
      hours: '4:00 PM - 8:00 PM',
      slots: [
        { id: 't4_s1', timeString: '04:00 PM - 05:00 PM', isAvailable: true },
        { id: 't4_s2', timeString: '05:30 PM - 06:30 PM', isAvailable: true },
        { id: 't4_s3', timeString: '07:00 PM - 08:00 PM', isAvailable: true },
      ],
    },
    reviews: [
      {
        id: 'rev_4_1',
        reviewerName: 'Daniel Scott',
        reviewerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 5,
        comment: 'Amazing conversational Spanish sessions. We talked about food, travel, and campus events. Elena corrects grammar errors gently.',
        date: 'May 22, 2026',
        skillName: 'Spanish Conversational Skills',
      },
    ],
  },
  {
    id: 'tutor_5',
    name: 'Michael Chang',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=120&h=120',
    dept: 'Finance & Analytics, Year 4',
    bio: 'Hey! I help students master MS Excel databases, financial modeling, and basic corporate finance concepts. I have a background in tutoring business statistics as well. Let us make numbers fun!',
    offeredSkills: ['Excel formulas & VBA', 'Corporate Financial Modeling', 'Business Statistics'],
    learningRequests: ['Git & Github Basics', 'React & Tailwind CSS'],
    rating: 4.9,
    reviewsCount: 16,
    totalSessions: 38,
    availabilitySchedule: {
      days: ['Mon', 'Tue', 'Thu'],
      hours: '1:00 PM - 5:00 PM',
      slots: [
        { id: 't5_s1', timeString: '01:00 PM - 02:00 PM', isAvailable: true },
        { id: 't5_s2', timeString: '02:30 PM - 03:30 PM', isAvailable: true },
        { id: 't5_s3', timeString: '04:00 PM - 05:00 PM', isAvailable: true },
      ],
    },
    reviews: [
      {
        id: 'rev_5_1',
        reviewerName: 'Aria Taylor',
        reviewerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=64&h=64',
        rating: 5,
        comment: 'Michael is fantastic! He made Excel Pivot Tables and VLOOKUP completely straightforward. I feel so ready for my business internship now!',
        date: 'May 24, 2026',
        skillName: 'Excel formulas & VBA',
      },
    ],
  },
];

export const SKILLS: Skill[] = [
  {
    id: 'skill_1',
    title: 'React & Tailwind CSS',
    category: 'Technology & Coding',
    description: 'Learn modern React hooks, state management, component hierarchies, and rapid responsive layout design using utility classes.',
    difficultyLevel: 'Intermediate',
    tutorId: 'tutor_1',
    tutorName: 'Alex Rivera',
    tutorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Computer Science, Year 3',
    rating: 4.9,
    reviewsCount: 12,
    creditsRate: 1, // 1 Exchange Credit / hour
    availabilityBadge: 'Available Today',
  },
  {
    id: 'skill_2',
    title: 'Python Data Science',
    category: 'Technology & Coding',
    description: 'Get started with NumPy, Pandas, and Matplotlib. Clean real data sets, compile stats, and build your first plotting charts.',
    difficultyLevel: 'Beginner',
    tutorId: 'tutor_1',
    tutorName: 'Alex Rivera',
    tutorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Computer Science, Year 3',
    rating: 4.8,
    reviewsCount: 6,
    creditsRate: 1,
    availabilityBadge: 'Evenings Only',
  },
  {
    id: 'skill_3',
    title: 'Figma UI/UX Prototyping',
    category: 'Design & Creative',
    description: 'Master Figma key fundamentals: Auto-layout, components, prototyping connections, and creating beautiful interface layouts.',
    difficultyLevel: 'Beginner',
    tutorId: 'tutor_2',
    tutorName: 'Chloe Tanaka',
    tutorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Digital Arts & Design, Year 4',
    rating: 5.0,
    reviewsCount: 15,
    creditsRate: 1,
    availabilityBadge: 'Available Today',
  },
  {
    id: 'skill_4',
    title: 'Vector Illustration',
    category: 'Design & Creative',
    description: 'Learn the pen tool, vector path properties, and color gradients to design original posters, app assets, and character graphics.',
    difficultyLevel: 'Intermediate',
    tutorId: 'tutor_2',
    tutorName: 'Chloe Tanaka',
    tutorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Digital Arts & Design, Year 4',
    rating: 5.0,
    reviewsCount: 7,
    creditsRate: 1,
    availabilityBadge: 'Flexible',
  },
  {
    id: 'skill_5',
    title: 'Calculus I & II Prep',
    category: 'Academics & Math',
    description: 'Struggling with integrals, limits, derivatives, or series convergence? Let us practice problem-solving step by step.',
    difficultyLevel: 'Intermediate',
    tutorId: 'tutor_3',
    tutorName: 'David Kim',
    tutorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Mechanical Engineering, Year 3',
    rating: 4.7,
    reviewsCount: 10,
    creditsRate: 1,
    availabilityBadge: 'Weekends',
  },
  {
    id: 'skill_6',
    title: '3D Modeling (SolidWorks)',
    category: 'Design & Creative',
    description: 'Create 3D components, assemblies, and detailed technical engineering drafts. Perfect for beginners and school design projects.',
    difficultyLevel: 'Intermediate',
    tutorId: 'tutor_3',
    tutorName: 'David Kim',
    tutorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Mechanical Engineering, Year 3',
    rating: 4.9,
    reviewsCount: 5,
    creditsRate: 1,
    availabilityBadge: 'Weekends',
  },
  {
    id: 'skill_7',
    title: 'Spanish Conversational Skills',
    category: 'Languages & Writing',
    description: 'Improve your speaking fluency. We will choose a fresh campus topic every session to expand your natural vocabulary and grammar patterns.',
    difficultyLevel: 'All Levels',
    tutorId: 'tutor_4',
    tutorName: 'Elena Rostova',
    tutorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Applied Linguistics, Year 2',
    rating: 4.8,
    reviewsCount: 12,
    creditsRate: 1,
    availabilityBadge: 'Evenings Only',
  },
  {
    id: 'skill_8',
    title: 'Excel formulas & VBA',
    category: 'Business & Finance',
    description: 'Learn simple database manipulation, pivot tables, lookup tables (XLOOKUP, VLOOKUP) and introductory automation macros.',
    difficultyLevel: 'Intermediate',
    tutorId: 'tutor_5',
    tutorName: 'Michael Chang',
    tutorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=120&h=120',
    tutorDept: 'Finance & Analytics, Year 4',
    rating: 4.9,
    reviewsCount: 16,
    creditsRate: 1,
    availabilityBadge: 'Flexible',
  },
];
